In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from IPython.display import SVG
from graphviz import Source
from IPython.display import display
from sklearn import tree

In [2]:
df = pd.read_csv('titanic.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df = df.drop(columns= ['PassengerId', 'Ticket', 'Cabin', 'Name'])

In [5]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [6]:
df.Sex = df.Sex.map({
    'male' : 1,
    'female' : 0

})

In [7]:
df.Embarked = df.Embarked.map({
    'S' : 1,
    'C' : 11,
    'Q' : 111
})

In [8]:
df

     Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0           0       3    1  22.0      1      0   7.2500       1.0
1           1       1    0  38.0      1      0  71.2833      11.0
2           1       3    0  26.0      0      0   7.9250       1.0
3           1       1    0  35.0      1      0  53.1000       1.0
4           0       3    1  35.0      0      0   8.0500       1.0
..        ...     ...  ...   ...    ...    ...      ...       ...
886         0       2    1  27.0      0      0  13.0000       1.0
887         1       1    0  19.0      0      0  30.0000       1.0
888         0       3    0   NaN      1      2  23.4500       1.0
889         1       1    1  26.0      0      0  30.0000      11.0
890         0       3    1  32.0      0      0   7.7500     111.0

[891 rows x 8 columns]

In [9]:
df.isna().any()

Survived    False
Pclass      False
Sex         False
Age          True
SibSp       False
Parch       False
Fare        False
Embarked     True
dtype: bool

In [10]:
df.Embarked = df.Embarked.fillna(1)
df

     Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0           0       3    1  22.0      1      0   7.2500       1.0
1           1       1    0  38.0      1      0  71.2833      11.0
2           1       3    0  26.0      0      0   7.9250       1.0
3           1       1    0  35.0      1      0  53.1000       1.0
4           0       3    1  35.0      0      0   8.0500       1.0
..        ...     ...  ...   ...    ...    ...      ...       ...
886         0       2    1  27.0      0      0  13.0000       1.0
887         1       1    0  19.0      0      0  30.0000       1.0
888         0       3    0   NaN      1      2  23.4500       1.0
889         1       1    1  26.0      0      0  30.0000      11.0
890         0       3    1  32.0      0      0   7.7500     111.0

[891 rows x 8 columns]

In [11]:
df = df.dropna(axis = 'rows')
df

     Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0           0       3    1  22.0      1      0   7.2500       1.0
1           1       1    0  38.0      1      0  71.2833      11.0
2           1       3    0  26.0      0      0   7.9250       1.0
3           1       1    0  35.0      1      0  53.1000       1.0
4           0       3    1  35.0      0      0   8.0500       1.0
..        ...     ...  ...   ...    ...    ...      ...       ...
885         0       3    0  39.0      0      5  29.1250     111.0
886         0       2    1  27.0      0      0  13.0000       1.0
887         1       1    0  19.0      0      0  30.0000       1.0
889         1       1    1  26.0      0      0  30.0000      11.0
890         0       3    1  32.0      0      0   7.7500     111.0

[714 rows x 8 columns]

In [12]:
x = df.drop(columns = [
    'Survived'
])
x

     Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         3    1  22.0      1      0   7.2500       1.0
1         1    0  38.0      1      0  71.2833      11.0
2         3    0  26.0      0      0   7.9250       1.0
3         1    0  35.0      1      0  53.1000       1.0
4         3    1  35.0      0      0   8.0500       1.0
..      ...  ...   ...    ...    ...      ...       ...
885       3    0  39.0      0      5  29.1250     111.0
886       2    1  27.0      0      0  13.0000       1.0
887       1    0  19.0      0      0  30.0000       1.0
889       1    1  26.0      0      0  30.0000      11.0
890       3    1  32.0      0      0   7.7500     111.0

[714 rows x 7 columns]

In [13]:
y = df.Survived
y

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: Survived, Length: 714, dtype: int64

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = 0.8)

In [15]:
y_test

556    1
614    0
606    0
695    0
774    1
      ..
870    0
484    1
257    1
588    0
728    0
Name: Survived, Length: 143, dtype: int64

In [16]:
model = DecisionTreeClassifier()
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [17]:
y_pred = model.predict(x_test)
y_pred

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0])

In [18]:
accuracy_score(y_test, y_pred)

0.7412587412587412

In [19]:
model_2 = DecisionTreeClassifier(criterion= 'entropy')
model_2.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [35]:
x_train

     Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
94        3    1  59.0      0      0   7.2500       1.0
813       3    0   6.0      4      2  31.2750       1.0
712       1    1  48.0      1      0  52.0000       1.0
348       3    1   3.0      1      1  15.9000       1.0
134       2    1  25.0      0      0  13.0000       1.0
..      ...  ...   ...    ...    ...      ...       ...
124       1    1  54.0      0      1  77.2875       1.0
720       2    0   6.0      0      1  33.0000       1.0
112       3    1  22.0      0      0   8.0500       1.0
516       2    0  34.0      0      0  10.5000       1.0
562       2    1  28.0      0      0  13.5000       1.0

[571 rows x 7 columns]

In [20]:
y_pred_2 = model_2.predict(x_test)
y_pred_2

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0])

In [21]:
accuracy_score(y_test, y_pred)

0.7412587412587412

In [22]:
accuracy_1 = model.score(x_train, y_train)
accuracy_1

0.989492119089317

In [23]:
accuracy_2 = model.score(x_test, y_test)
accuracy_2

0.7412587412587412

In [24]:
model = DecisionTreeClassifier()
params = {
    "criterion" : ['gini', 'entropy', 'log_loss'],
    "max_depth" : range(1,20),
    "min_samples_split" : range(3, 20),
    "min_samples_leaf" : range(1, 23)
}

In [25]:
gscv = GridSearchCV(estimator = model, param_grid= params, n_jobs = -1, cv = 5)

In [26]:
gscv.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': range(1, 20),
                         'min_samples_leaf': range(1, 23),
                         'min_samples_split': range(3, 20)})

In [27]:
gscv.best_params_

{'criterion': 'log_loss',
 'max_depth': 9,
 'min_samples_leaf': 5,
 'min_samples_split': 14}

In [28]:
gscv.best_score_

0.8055682684973302

In [29]:
best_model = gscv.best_estimator_
best_model

DecisionTreeClassifier(criterion='log_loss', max_depth=9, min_samples_leaf=5,
                       min_samples_split=14)

In [36]:
t = [3, 1, 17.0, 1, 0, 30.0000, 1.0]

In [38]:
df = pd.array
df

In [39]:
gscv.predict(df)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

TypeError: float() argument must be a string or a real number, not 'function'